
package com.productcache.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProductCacheBuilderPDT802X1HttpService", targetNamespace = "http://ei/product/product_cache_builder_pdt802x1_http", wsdlLocation = "file:/C:/Users/EmilioFlores/eclipse-workspace_new/converter/src/main/resources/wsdl/ProductCacheBuilderPDT802X1Http.wsdl")
public class ProductCacheBuilderPDT802X1HttpService
    extends Service
{

    private static final URL PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_WSDL_LOCATION;
    private static final WebServiceException PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_EXCEPTION;
    private static final QName PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_QNAME = new QName("http://ei/product/product_cache_builder_pdt802x1_http", "ProductCacheBuilderPDT802X1HttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/EmilioFlores/eclipse-workspace_new/converter/src/main/resources/wsdl/ProductCacheBuilderPDT802X1Http.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_WSDL_LOCATION = url;
        PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_EXCEPTION = e;
    }

    public ProductCacheBuilderPDT802X1HttpService() {
        super(__getWsdlLocation(), PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_QNAME);
    }

    public ProductCacheBuilderPDT802X1HttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_QNAME, features);
    }

    public ProductCacheBuilderPDT802X1HttpService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_QNAME);
    }

    public ProductCacheBuilderPDT802X1HttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_QNAME, features);
    }

    public ProductCacheBuilderPDT802X1HttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCacheBuilderPDT802X1HttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductCacheBuilderPDT802X1
     */
    @WebEndpoint(name = "ProductCacheBuilderPDT802X1HTTP_ProductCacheBuilderPDT802X1HttpPort")
    public ProductCacheBuilderPDT802X1 getProductCacheBuilderPDT802X1HTTPProductCacheBuilderPDT802X1HttpPort() {
        return super.getPort(new QName("http://ei/product/product_cache_builder_pdt802x1_http", "ProductCacheBuilderPDT802X1HTTP_ProductCacheBuilderPDT802X1HttpPort"), ProductCacheBuilderPDT802X1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCacheBuilderPDT802X1
     */
    @WebEndpoint(name = "ProductCacheBuilderPDT802X1HTTP_ProductCacheBuilderPDT802X1HttpPort")
    public ProductCacheBuilderPDT802X1 getProductCacheBuilderPDT802X1HTTPProductCacheBuilderPDT802X1HttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ei/product/product_cache_builder_pdt802x1_http", "ProductCacheBuilderPDT802X1HTTP_ProductCacheBuilderPDT802X1HttpPort"), ProductCacheBuilderPDT802X1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_EXCEPTION!= null) {
            throw PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_EXCEPTION;
        }
        return PRODUCTCACHEBUILDERPDT802X1HTTPSERVICE_WSDL_LOCATION;
    }

}
